### ISSUE TITLE
Offline reagent bank is (partly) empty after login

### ISSUE THREAD

**Issue by cremor** [gsnerf/Baud-Bag#17] opened 2024-08-23 16:36 UTC
When I login a char, the offline reagent bank is often (always?) either completely empty, or shows empty slots that are not empty.
Visiting a bank fixes the offline bank display.
A UI reload does not trigger the bug. A full relog is needed.

I'm using addon version 11.0.2.4 right now, but I also noticed this before with older versions.

**Comment by gsnerf** [comment] 2024-08-25 18:52
When this happens, can you please check if simply closing and reopening the offline bank will already fix this? I think I have seen this before with this behavior, but I didn't get around to identify the root cause yet. Might be the cache not being loaded at the correct time.

**Comment by cremor** [comment] 2024-08-25 19:16
I sometimes get a similar error where the icons are missing in the offline bank, but stack counts are still showing. That problem is fixed by closing and reopening the offline bank. And that error is very old.

The new error that I'm reporting here doesn't even show stack counts in the affected slots. And closing and reopening does not fix the new error.

**Comment by gsnerf** [comment] 2024-09-07 22:31
With 11.0.2.5 I rewrote big parts of caching and item loading. With that the issue should be hopefully gone. I'll close for now, if you still encounter this issue, feel free to reopen.

**Closed by gsnerf** 2024-09-07 22:31 UTC

**Comment by cremor** [comment] 2024-09-08 16:38
I still get this issue with v11.0.2.5
